model:
  imagebind_ckpt_path: "/mnt/bd/yiren-bytedrive/cache_dir/ImageBind"
  vicuna_ckpt_path: "lmsys/vicuna-7b-v1.3"
  max_tgt_len: 32
  stage: 1
  lora_r: 32
  lora_alpha: 32
  lora_dropout: 0.1
  penalty_alpha: 0.6
  top_k: 10
  top_p: 0.7
  random_prefix_len: 5
  sample_num: 2
  decoding_method: "sampling"
  generate_len: 512

preprocess:
    vis_processor:
        train:
          name: "alpro_video_train"
          image_size: 224
          n_frms: 4
        eval:
          name: "alpro_video_eval"
          image_size: 224
          n_frms: 8
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"